Update ORL.FRP.Editor.asmdef
Fixed errors that occur on build.
Example: `error CS0234: The type or namespace name 'EditorTools' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)`